// Auto-generated by script/sync_addresses.mjs
// Source of truth: deployments/addresses.json

export const ADDRS = {
  hook: "0x2b57c62cf6030e275b325bbbbea8964c287d50c0" as const,
  reactive: "0x1fb5b9658aa39bd26bc9bfbc33970a4a238a6678" as const,
  usdc: "0xD1377445CD5069Cc53ad4661d917EB41f70b0377" as const,
  react: "0x769e0F7cF8F4b0c20971BEF0780C3DE31d0DB7d6" as const,
  swapExecutor: "0x89c5C45794fe236dA8823Ab00110B4a5cFc8a64F" as const,
  callbackProxy: "0x9299472A6399Fd1027ebF067571Eb3e3D7837FC4" as const,
};

export const POOL_MANAGER = "0x00B036B58a818B1BC34d502D3fE730Db729e62AC" as const;
export const CHAIN_ID = 1301 as const;

export const LASNA = {
  chainId: 5318007 as const,
  reactiveTwamm: "0x13dD8AC2311125a0f84Ae8095060770F1f9c07b5" as const,
  systemContract: "0x0000000000000000000000000000000000fffFfF" as const,
};
