// Auto-generated by script/sync_addresses.mjs
// Source of truth: deployments/addresses.json

export const ADDRS = {
  hook: "0x2b57c62cf6030e275b325bbbbea8964c287d50c0" as const,
  reactive: "0x1fb5b9658aa39bd26bc9bfbc33970a4a238a6678" as const,
  usdc: "0x4148e16C6C02dD56b42c638989cF419733468f61" as const,
  react: "0x3fdC17469956C6111a6ddf88205D5a1c16E0433e" as const,
  swapExecutor: "0xBFA42771C34B2f60a9f1f9b1Ca507C8e18Cb5F59" as const,
  callbackProxy: "0x9299472A6399Fd1027ebF067571Eb3e3D7837FC4" as const,
};

export const POOL_MANAGER = "0x00B036B58a818B1BC34d502D3fE730Db729e62AC" as const;
export const CHAIN_ID = 1301 as const;

export const LASNA = {
  chainId: 5318007 as const,
  reactiveTwamm: "0x13dD8AC2311125a0f84Ae8095060770F1f9c07b5" as const,
  systemContract: "0x0000000000000000000000000000000000fffFfF" as const,
};
