// Auto-generated by script/sync_addresses.mjs
// Source of truth: deployments/addresses.json

import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";
import ReactiveTWAMMAbi from "~~/contracts/abi/ReactiveTWAMM.json";
import TWAMMHookAbi from "~~/contracts/abi/TWAMMHook.json";

const externalContracts = {
  1301: {
    TWAMMHook: {
      address: "0x323cDD447000e5F9CCF1E07444898A92548410C0",
      abi: TWAMMHookAbi,
    },
    ReactiveTWAMM: {
      address: "0xA7F2D45929c76A2ea5af3aB29d3CF3Ac09Bd4017",
      abi: ReactiveTWAMMAbi,
    },
  },
} as const;

export default externalContracts as GenericContractsDeclaration;
