// Auto-generated by script/sync_addresses.mjs
// Source of truth: deployments/addresses.json

import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";
import ReactiveTWAMMAbi from "~~/contracts/abi/ReactiveTWAMM.json";
import TWAMMHookAbi from "~~/contracts/abi/TWAMMHook.json";

const externalContracts = {
  1301: {
    TWAMMHook: {
      address: "0x2b57c62cf6030e275b325bbbbea8964c287d50c0",
      abi: TWAMMHookAbi,
    },
    ReactiveTWAMM: {
      address: "0x1fb5b9658aa39bd26bc9bfbc33970a4a238a6678",
      abi: ReactiveTWAMMAbi,
    },
  },
} as const;

export default externalContracts as GenericContractsDeclaration;
