#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), "..");
const src = path.join(root, "deployments", "addresses.json");
const outEnv = path.join(root, ".env.addresses");
const outFrontend = path.join(root, "frontend", "app", "addresses.ts");

const data = JSON.parse(fs.readFileSync(src, "utf8"));
const u = data.unichainSepolia;
const l = data.reactiveLasna;

const env = `# Auto-generated from deployments/addresses.json\n# Source of truth: deployments/addresses.json\n\nUNICHAIN_CHAIN_ID=${u.chainId}\nUNICHAIN_POOL_MANAGER=${u.poolManager}\nREACTIVE_CALLBACK_UNICHAIN=${u.reactiveCallbackProxy}\nTWAMM_HOOK=${u.twammHook}\nREACTIVE_TWAMM=${u.reactiveTwamm}\n\n# Canonical demo token/executor vars\nUSDC_ADDRESS=${u.demo.usdc}\nREACT_ADDRESS=${u.demo.react}\nSWAP_EXECUTOR_ADDRESS=${u.demo.swapExecutor}\n\n# Compatibility aliases (used by arb_bot + older scripts)\nUSDC=${u.demo.usdc}\nREACT_TOKEN=${u.demo.react}\nSWAP_EXECUTOR=${u.demo.swapExecutor}\n\nLASNA_CHAIN_ID=${l.chainId}\nLASNA_REACTIVE_TWAMM=${l.reactiveTwamm}\nREACTIVE_CALLBACK_LASNA=${l.reactiveCallbackProxy}\n`;

const fe = `// Auto-generated by script/sync_addresses.mjs\n// Source of truth: deployments/addresses.json\n\nexport const ADDRS = {\n  hook: "${u.twammHook}" as const,\n  reactive: "${u.reactiveTwamm}" as const,\n  usdc: "${u.demo.usdc}" as const,\n  react: "${u.demo.react}" as const,\n  swapExecutor: "${u.demo.swapExecutor}" as const,\n};\n\nexport const POOL_MANAGER = "${u.poolManager}" as const;\nexport const CHAIN_ID = ${u.chainId} as const;\n\nexport const LASNA = {\n  chainId: ${l.chainId} as const,\n  reactiveTwamm: "${l.reactiveTwamm}" as const,\n};\n`;

fs.writeFileSync(outEnv, env);
fs.writeFileSync(outFrontend, fe);

// Also patch .env so forge auto-loads addresses (forge only reads .env, not .env.addresses)
const dotenv = path.join(root, ".env");
if (fs.existsSync(dotenv)) {
  const marker = "# --- AUTO-SYNCED ADDRESSES (do not edit below) ---";
  let content = fs.readFileSync(dotenv, "utf8");
  const markerIdx = content.indexOf(marker);
  if (markerIdx !== -1) {
    content = content.slice(0, markerIdx);
  }
  content = content.trimEnd() + "\n\n" + marker + "\n" + env;
  fs.writeFileSync(dotenv, content);
  console.log("-", ".env (address section updated)");
}

console.log("Synced addresses:");
console.log("-", path.relative(root, outEnv));
console.log("-", path.relative(root, outFrontend));
